---    
- name: Gather VPC facts
  ec2_vpc_net_facts:
    region: "{{ region }}"
    filters:
      "tag:Name": "{{ vpc_id }}"
  register: vpcs

- debug: 
    msg: "{{ vpcs }}"

- name: Setting the fact for a VPC
  set_fact: vpc="{{ vpcs.vpcs[0] }}"

- name: Set VPC Subnets facts
  ec2_vpc_subnet_facts:
    region: "{{ region }}"
    filters:
      vpc-id: "{{ vpc.id }}"
  register: subnets_facts